### ISSUE TITLE
Soundex Installation Fails

### ISSUE THREAD

**Issue by simonefrancia** [libindic/soundex#17]
```ModuleNotFoundError: No module named 'libindic.utils'```

I cannot install Soundex, this error appears after following these commands:
```
git clone https://github.com/libindic/soundex.git
cd soundex
python setup.py sdist
pip install dist/libindic-soundex*.tar.gz
```

Thanks

**Comment by simonefrancia** [comment]
I figured out adding by hand folder missing, searching on official libindic repos on web

**Comment by santhoshtr** [comment]
It is a valid issue. Need to fix.

**Comment by jack-rory-staunton** [comment]
having the same issue
