### ISSUE TITLE
compare function doesn't work

### ISSUE THREAD

**Issue by nickzuck** [libindic/soundex#4]
soundex.compare function doesn't seems to work

**Comment by arushidogra** [comment]
It is working ..

![screenshot from 2016-03-04 18 56 55](https://cloud.githubusercontent.com/assets/9354396/13528310/106f4eaa-e23b-11e5-9d21-ef28353b703f.png)

**Comment by nickzuck** [comment]
Never mind I have written my own soundex to make that work for the website . You can checkout the soundex [implementation at link](https://github.com/nickzuck/Data-Structures-and-Algorithms/blob/master/soundex.py)
