### ISSUE TITLE
Not showing proper results

### ISSUE THREAD

**Issue by arushidogra** [libindic/soundex#9]
There is some problem with the results of soundex.
![screenshot from 2016-03-07 14 06 31](https://cloud.githubusercontent.com/assets/9354396/13564241/2875533e-e46e-11e5-8f0e-3ba51c17b32d.png)
![screenshot from 2016-03-07 14 07 04](https://cloud.githubusercontent.com/assets/9354396/13564242/28f2a532-e46e-11e5-8e56-c000c88e8945.png)

**Comment by arushidogra** [comment]
Console is also giving the same results 
![screenshot from 2016-03-07 14 16 04](https://cloud.githubusercontent.com/assets/9354396/13564369/2825b940-e46f-11e5-9e00-96a1f837df1e.png)

**Comment by copyninja** [comment]
Please feel free to do  the investigation and fix as required. Also please add tests to confirm that those changes are actually fixing the changes done by you.

**Comment by arushidogra** [comment]
Tests for the previous issue?

**Comment by copyninja** [comment]
Please check it yourself. I assume you know how to run python tests.
